<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

if(!isset($_SESSION['perfil'])){
    Layout::includeLayout('nologinnav');
}
else if($_SESSION['perfil']==1){
    Layout::includeLayout('usernav');
}
else if($_SESSION['perfil']==2){
    Layout::includeLayout('adminnav');
}
else if($_SESSION['perfil']==3){
    Layout::includeLayout('gestornav');
}
else if($_SESSION['perfil']==4){
    Layout::includeLayout('operadorNav');
}?>




<?php Layout::includeLayout('footer')?>