<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
use ArmoredCore\WebObjects\URL;


?>

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Silvio Priem Mendes, PhD">

    <title>Weblogic MVC</title>

    <?= AssetBundler::css() ?>

    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png') ?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css') ?>" media="screen">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!--<link rel="stylesheet" href="<?php //Asset::css('/navbar.css') ?>">
    HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js') ?>"></script>
    <script src="<?= Asset::js('respond.min.js') ?>"></script>
    <![endif]-->
</head>

<body class="home">
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul style="margin-left: 40%" class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="<?= URL::toRoute('home/index') ?>">Inicio <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="<?= URL::toRoute('voo/ListarVoos') ?>">Voos Disponiveis <span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?= URL::toRoute('passagemvenda/HistoricoPassagem') ?>">PassagensCompradas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?= URL::toRoute('user/destroysession')?>">Logout</a>
            </li>
        </ul>
    </div>
</nav>
<!-- /.navbar -->