<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

if(!isset($_SESSION['perfil'])){
    Layout::includeLayout('nologinnav');
}
else if($_SESSION['perfil']==1){
    Layout::includeLayout('usernav');
}

$escalas= Data::get('escalas');
$origens= Data::get('origem');
$destinos= Data::get('destino');
?>

<head>
    <meta charset="UTF-8">
    <title>Gestão Escalas</title>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<body>

<?php

echo '<h1>Escalas</h1>';
?>
<button href="<?= Url::toRoute('escala/')?>"class="btn btn-success">Inserir Escala</button>
<form>
    <?php
    foreach ($escalas as $escala){

        foreach($origens as $origem)
        {
            foreach($destinos as $destino)
            {
                echo '<hr>';

                echo 'Id da Escala: ' . $escala->id_escala;

                echo '<br>Distância: ' . $escala->distancia;

                echo '<br>Data: ' . $escala->data;

                echo '<br>Aeroporto de partida:' . $origem->nome_aeroporto;


                echo '<br>Aeroporto de Chegada:'. $destino->nome_aeroporto;
                ?>
                <div>

                    <br><a href="<?= Url::toRoute('escala/edit',$escala->id_escala)?>">Editar</a>

                    <br><a href="<?= Url::toRoute('escala/destroy',$escala->id_escala)?>">Eliminar</a>

                </div>
                <?php
            }

        }
    }
    ?>
</form>
</body>

