<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

$aeroportos=Data::get('aeroportos');
$avioes=Data::get('avioes');

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Nova Escala</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../../../public/css/edit.css">
</head>
<body>

<div class="container register-form">
    <div class="form">
        <form method="post" action="<?=URL::toRoute('escala/store')?>">
            <div class="titulo">
                <h1>Nova Escala</h1>
            </div>

            <div class="form-content">
                <div class="row">
                    <div class="col-md-4 left">
                        <div class="form-group">
                            <input type="time" class="form-control" placeholder="Distancia" value="" name="distancia"/>
                        </div>
                        <div class="form-group">
                            <input type="datetime-local" class="form-control" placeholder="Data" value="" name="data"/>
                        </div>
                        <div class="form-group">

                        </div>
                    </div>
                    <div class="col-md-4 right">
                        <select name="origem">
                            <?php
                            foreach ($aeroportos as $aeroporto)
                            {
                                ?>
                                <option value="<?=$aeroporto->id_aeroporto?>"><?=$aeroporto->nome_aeroporto?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <br><br>
                        <div class="form-group">
                            <select name="destino">
                                <?php
                                foreach ($aeroportos as $aeroporto)
                                {
                                    ?>
                                    <option value="<?=$aeroporto->id_aeroporto?>"><?=$aeroporto->nome_aeroporto?></option>
                                    <?php
                                }
                                ?>
                            </select>
                            <br><br>
                            <div class="form-group">
                                <select name="id_aviao" id="id_aviao">
                                <?php
                                foreach ($avioes as $aviao)
                                {
                                    ?>
                                    <option value="<?=$aviao->id_aviao?>"><?=$aviao->referencia . "-" . $aviao->tipo_aviao?></option>
                                    <?php
                                }
                                ?>
                                </select>
                            </div>
                            <br>
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </div>
        </form>
    </div>