<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

$aeroporto = Data::get('aeroporto') ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Editar Informações</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../../../public/css/edit.css">
</head>
<body>

<div class="container register-form">
    <div class="form">
        <form method="post" action="<?=URL::toRoute('aeroporto/update',$aeroporto->id_aeroporto)?>">
            <div class="titulo">
                <h1>Informações de Utilizador</h1>
            </div>

            <div class="form-content">
                <div class="row">
                    <div class="col-md-4 left">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Nome do Aeroporto" value="<?=$aeroporto->nome_aeroporto?>" name="nome_aeroporto"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Localidade" value="<?=$aeroporto->localidade?>" name="localidade"/>
                            <button type="submit" class="btnSubmit">Submit</button>
                    </div>
                </div>
            </div>
    </div>
    </form>
</div>