<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

if(!isset($_SESSION['perfil'])){
    Layout::includeLayout('nologinnav');
}
else if($_SESSION['perfil']==1){
    Layout::includeLayout('usernav');
}

$aeroportos= Data::get('aeroportos');
?>

<head>
    <meta charset="UTF-8">
    <title>Gestão Aeroportos</title>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="<?= Asset::css('/index.css')?>">

</head>
<h1>Aeroportos</h1>
<a href="<?= Url::toRoute('aeroporto/create')?>" class="btn btn-success">Inserir Aeroporto</a>

<table id="#myTable">
    <thead>
    <tr>
        <th>
            ID do Aeroporto
        </th>
        <th>
            Nome do Aeroporto
        </th>
        <th>
            Localidade
        </th>
    </tr>
    </thead>
        <tbody>
        <?php foreach ($aeroportos as $aeroporto) { ?>
        <tr>
            <td><?=$aeroporto->id_aeroporto?></td>
            <td><?=$aeroporto->nome_aeroporto?></td>
            <td><?=$aeroporto->localidade?></td>
            <td><a href="<?= Url::toRoute('aeroporto/edit',$aeroporto->id_aeroporto)?>">Edit</a> </td>
            <td><a href="<?= Url::toRoute('aeroporto/destroy',$aeroporto->id_aeroporto)?>">Delete</a> </td>
        </tr>
        </tbody>
        <?php } ?>
</table>