<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Novo Aeroporto</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../../../public/css/edit.css">
</head>
<body>

<div class="container register-form">
    <div class="form">
        <form method="post" action="<?=URL::toRoute('aeroporto/store')?>">
            <div class="titulo">
                <h1>Novo Aeroporto</h1>
            </div>

            <div class="form-content">
                <div class="row">
                    <div class="col-md-4 left">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Nome Aeroporto" value="" name="nome_aeroporto"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Localidade" value="" name="localidade"/>
                        </div>
                    </div>
                    <div class="col-md-4 right">
                        <div class="form-group">
                            <br>
                            <button type="submit" class="btnSubmit">Submit</button>
                        </div>
                    </div>
                </div>
        </form>
    </div>