<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

$aviao = Data::get('aviao') ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Editar Informações</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../../../public/css/edit.css">
</head>
<body>

<div class="container register-form">
    <div class="form">
        <form method="post" action="<?=URL::toRoute('aviao/update',$aviao->id_aviao)?>">
            <div class="titulo">
                <h1>Informações do Avião</h1>
            </div>

            <div class="form-content">
                <div class="row">
                    <div class="col-md-4 left">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Referência" value="<?=$aviao->referencia?>" name="referencia"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Lotação" value="<?=$aviao->lotacao?>" name="lotacao"/>
                        </div>
                    </div>
                    <div class="col-md-4 right">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Localidade" value="<?=$aviao->tipo_aviao?>" name="tipo_aviao"/>
                            <br>
                            <button type="submit" class="btnSubmit">Submit</button>
                        </div>
                </div>
            </div>
        </form>
    </div>