<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

?>

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author"      content="Silvio Priem Mendes, PhD">

    <title>Weblogic MVC</title>


    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png')?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css')?>" media="screen" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="../layout/forms.css">
    <link rel="stylesheet" href="<?= Asset::css('/login.css')?>">


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js')?>"></script>
    <script src="<?= Asset::js('respond.min.js')?>"></script>
    <![endif]-->
</head>

<body>
    <form  method="post" id="form" action="<?=Url::toRoute('user/processLogin')?>">
        <div class="row">
            <div class="col-md-4">
                <h3>Dados de Acesso</h3>
                 <input type="text" class="form-control" name="username" placeholder="Username"><br>
                 <input type="text" class="form-control" name="password" placeholder="Password">
            </div>
        </div>
            <div class="col-md-4">
                <input  type="submit" class="btn btn-success" value="Login">
            </div>
        </div>

    </form>
</body>