<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

if(!isset($_SESSION['perfil'])){
    Layout::includeLayout('nologinnav');
}
else if($_SESSION['perfil']==1){
    Layout::includeLayout('usernav');
}
else if($_SESSION['perfil']==3){
    Layout::includeLayout('gestornav');
}


$voos= Data::get('voos');
$origens= Data::get('origem');
$destinos= Data::get('destino');
?>

<head>
    <meta charset="UTF-8">
    <title>Gestão Voos</title>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<body>

<?php

echo '<h1>Voos Disponiveis</h1>';
?>
<a href="<?= Url::toRoute('voo/create')?>" class="btn btn-success">Inserir Voo</a>
<form>
    <?php
    foreach ($voos as $voo){

        foreach($origens as $origem)
        {
            foreach($destinos as $destino)
            {
                echo '<hr>';

                echo 'Id do Voo: ' . $voo->id_voo;

                echo '<br>Preço: ' . $voo->preco_voo;

                echo '<br>Aeroporto de partida:' . $origem->nome_aeroporto;


                echo '<br>Aeroporto de Chegada:'. $destino->nome_aeroporto;
?>
                <div>

                <br><a href="<?= Url::toRoute('voo/edit',$voo->id_voo)?>">Editar</a>

                <br><a href="<?= Url::toRoute('voo/destroy',$voo->id_voo)?>">Eliminar</a>

                </div>
<?php
            }

        }
    }
    ?>
</form>
</body>

