<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

if(!isset($_SESSION['perfil'])){
    Layout::includeLayout('nologinnav');
}
else if($_SESSION['perfil']==1){
    Layout::includeLayout('usernav');
}

$voos= Data::get('voos');
$origens= Data::get('origem');
$destinos= Data::get('destino');
?>

<head>
    <meta charset="UTF-8">
    <title>Gestão Voos</title>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="<?= Asset::css('/index.css')?>">

</head>

<?php

    echo '<h1>Voos Disponiveis</h1>';
    foreach ($voos as $voo){

         foreach($origens as $origem)
         {
            foreach($destinos as $destino)
            {
                echo '<hr>';

                echo 'Data de Compra: ' . $voo->id_voo;

                echo '<br>Preço: ' . $voo->preco_voo;

                echo '<br>Aeroporto de partida:' . $origem->nome_aeroporto;


                echo '<br>Aeroporto de Chegada:'. $destino->nome_aeroporto;
            }
        }
    }